### ISSUE TITLE
SlaveRefCount

### ISSUE THREAD

**Issue by Scitz0** [drftpd-ng/drftpd#52]
There seem to be some issues with the SlaveRefCount variable for vfs inodes.

The first issue is that json-io fails to deserialize the the AtomicInteger in the _slaveRefCounts variable giving it a default value of 0 when master loads the inode. Issue raised with json-io project.

The second issue noticed is regarding doSITE_FIXSLAVECOUNT(). For some reason the first child in directory seem to get the _slaveRefCounts value from the parent.

**Comment by Scitz0** [comment]
First issue solved by json-io project, json-io updated 8169252a046624a7a830b2e305f564dcfd47fb0a

**Comment by zer0c0nf** [comment]
thx 👍

**Comment by epochyx** [comment]
I'm not seeing that issue, can you provide details about the platform it's happening on? And a scenario to reproduce?

**Comment by zc0nf** [comment]
other problem, ive manually purged TV-HD directory (rm -Rf...)
```
site remerge slave_1
site rebuildindex
```

TV-HD = Empty, but size : 650,99 MB

```
[R] SIZE /TV-HD/
[R] 213 682610252
```

`cat userdata/vfs/TV-HD/.dirProperties`

```
{
  "@type":"org.drftpd.master.vfs.VirtualFileSystemDirectory",
  "_size":682610252,
  "_placeHolderLastModified":false,
  "_slaveRefCounts":{
    "@type":"java.util.TreeMap",
    "ARCHiVES":{
      "@type":"java.util.concurrent.atomic.AtomicInteger",
      "value":17
    },
    "slave_1":{
      "@type":"java.util.concurrent.atomic.AtomicInteger",
      "value":0
    }
  },
  "_username":"drftpd",
  "_group":"drftpd",
  "_keyedMap":{

  },
  "_pluginMap":{

  },
  "_untypedPluginMap":{
    "@type":"java.util.TreeMap"
  },
  "_lastModified":1611926207034,
  "_creationTime":1602593512394
}
```

and ARCHiVES slave no longer exist but still persist in .dirProperties...

```
[R] site slaves
[R] 200- slave_1: ONLINE ( UP: 0 @ 0B/s )-( DN: 0 @ 0B/s )-( DF: 898.5GB/960.7GB ).
[R] 200 OK, 1 slaves listed.
```

**Comment by tsautier** [comment]
@mvangoor @hrxcodes for review
